[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
khrypto_escrow = "F64yExtSv3K2k11TCa1j3fXsiU3Vygcpb7UWZSAjsb4L"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../../keys/oracle-devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
